import { useState, useEffect } from 'react';

export type Language = 'en' | 'hi' | 'es' | 'fr' | 'de' | 'it' | 'pt' | 'ar' | 'zh' | 'ja' | 'ru' | 'ko';

export const languages = [
  { code: 'en', name: 'English', flag: '🇬🇧' },
  { code: 'hi', name: 'हिन्दी', flag: '🇮🇳' },
  { code: 'es', name: 'Español', flag: '🇪🇸' },
  { code: 'fr', name: 'Français', flag: '🇫🇷' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪' },
  { code: 'it', name: 'Italiano', flag: '🇮🇹' },
  { code: 'pt', name: 'Português', flag: '🇵🇹' },
  { code: 'ar', name: 'العربية', flag: '🇸🇦' },
  { code: 'zh', name: '中文', flag: '🇨🇳' },
  { code: 'ja', name: '日本語', flag: '🇯🇵' },
  { code: 'ru', name: 'Русский', flag: '🇷🇺' },
  { code: 'ko', name: '한국어', flag: '🇰🇷' },
];

const translations: Record<string, Record<Language, string>> = {
  // Navigation
  'materials': {
    en: 'Materials',
    hi: 'सामग्री',
    es: 'Materiales',
    fr: 'Matériaux',
    de: 'Materialien',
    it: 'Materiali',
    pt: 'Materiais',
    ar: 'المواد',
    zh: '材料',
    ja: '素材',
    ru: 'Материалы',
    ko: '자료',
  },
  'gallery': {
    en: 'Gallery',
    hi: 'गैलरी',
    es: 'Galería',
    fr: 'Galerie',
    de: 'Galerie',
    it: 'Galleria',
    pt: 'Galeria',
    ar: 'المعرض',
    zh: '画廊',
    ja: 'ギャラリー',
    ru: 'Галерея',
    ko: '갤러리',
  },
  'about': {
    en: 'About',
    hi: 'हमारे बारे में',
    es: 'Acerca de',
    fr: 'À propos',
    de: 'Über',
    it: 'Chi siamo',
    pt: 'Sobre',
    ar: 'حول',
    zh: '关于',
    ja: '概要',
    ru: 'О нас',
    ko: '소개',
  },
  'contact': {
    en: 'Contact',
    hi: 'संपर्क',
    es: 'Contacto',
    fr: 'Contact',
    de: 'Kontakt',
    it: 'Contatto',
    pt: 'Contato',
    ar: 'اتصل',
    zh: '联系',
    ja: '連絡先',
    ru: 'Контакт',
    ko: '연락처',
  },
  'login': {
    en: 'Login',
    hi: 'लॉगिन',
    es: 'Iniciar sesión',
    fr: 'Connexion',
    de: 'Anmelden',
    it: 'Accedi',
    pt: 'Entrar',
    ar: 'تسجيل الدخول',
    zh: '登录',
    ja: 'ログイン',
    ru: 'Войти',
    ko: '로그인',
  },
  'admin': {
    en: 'Admin',
    hi: 'व्यवस्थापक',
    es: 'Administrador',
    fr: 'Administrateur',
    de: 'Administrator',
    it: 'Amministratore',
    pt: 'Administrador',
    ar: 'مسؤل',
    zh: '管理员',
    ja: '管理者',
    ru: 'Администратор',
    ko: '관리자',
  },
  'search': {
    en: 'Search materials...',
    hi: 'सामग्री खोजें...',
    es: 'Buscar materiales...',
    fr: 'Rechercher des matériaux...',
    de: 'Materialien suchen...',
    it: 'Cerca materiali...',
    pt: 'Pesquisar materiais...',
    ar: 'ابحث عن المواد...',
    zh: '搜索材料...',
    ja: '素材を検索...',
    ru: 'Искать материалы...',
    ko: '자료 검색...',
  },
  'developerBy': {
    en: 'Developed by',
    hi: 'द्वारा विकसित',
    es: 'Desarrollado por',
    fr: 'Développé par',
    de: 'Entwickelt von',
    it: 'Sviluppato da',
    pt: 'Desenvolvido por',
    ar: 'طور بواسطة',
    zh: '开发者',
    ja: '開発者',
    ru: 'Разработано',
    ko: '개발자',
  },
  'imageGallery': {
    en: 'Image Gallery',
    hi: 'छवि गैलरी',
    es: 'Galería de Imágenes',
    fr: 'Galerie d\'Images',
    de: 'Bildergalerie',
    it: 'Galleria di Immagini',
    pt: 'Galeria de Imagens',
    ar: 'معرض الصور',
    zh: '图片库',
    ja: '画像ギャラリー',
    ru: 'Галерея изображений',
    ko: '이미지 갤러리',
  },
  'browseCollection': {
    en: 'Browse our curated collection organized in beautiful categories',
    hi: 'सुंदर श्रेणियों में व्यवस्थित हमारे संग्रह को ब्राउज़ करें',
    es: 'Explore nuestra colección organizada en hermosas categorías',
    fr: 'Parcourez notre collection organisée en belles catégories',
    de: 'Durchsuchen Sie unsere kuratierte Sammlung in schönen Kategorien',
    it: 'Sfoglia la nostra collezione organizzata in bellissime categorie',
    pt: 'Navegue pela nossa coleção organizada em belas categorias',
    ar: 'تصفح مجموعتنا المنظمة في فئات جميلة',
    zh: '浏览我们精心策划的美丽分类集合',
    ja: '美しいカテゴリーに整理されたコレクションを閲覧',
    ru: 'Просмотрите нашу коллекцию, организованную в красивые категории',
    ko: '아름다운 카테고리로 구성된 컬렉션 탐색',
  },
  'searchImages': {
    en: 'Search images...',
    hi: 'छवियां खोजें...',
    es: 'Buscar imágenes...',
    fr: 'Rechercher des images...',
    de: 'Bilder suchen...',
    it: 'Cerca immagini...',
    pt: 'Pesquisar imagens...',
    ar: 'البحث عن الصور...',
    zh: '搜索图片...',
    ja: '画像を検索...',
    ru: 'Искать изображения...',
    ko: '이미지 검색...',
  },
  'newest': {
    en: 'Newest',
    hi: 'नवीनतम',
    es: 'Más reciente',
    fr: 'Plus récent',
    de: 'Neueste',
    it: 'Più recente',
    pt: 'Mais recente',
    ar: 'الأحدث',
    zh: '最新',
    ja: '最新',
    ru: 'Новейшие',
    ko: '최신',
  },
  'oldest': {
    en: 'Oldest',
    hi: 'सबसे पुराना',
    es: 'Más antiguo',
    fr: 'Plus ancien',
    de: 'Älteste',
    it: 'Più vecchio',
    pt: 'Mais antigo',
    ar: 'الأقدم',
    zh: '最旧',
    ja: '最古',
    ru: 'Старейшие',
    ko: '오래된',
  },
  'featured': {
    en: 'Featured',
    hi: 'फीचर्ड',
    es: 'Destacado',
    fr: 'En vedette',
    de: 'Hervorgehoben',
    it: 'In evidenza',
    pt: 'Destaque',
    ar: 'مميز',
    zh: '精选',
    ja: '注目',
    ru: 'Избранное',
    ko: '추천',
  },
  'images': {
    en: 'images',
    hi: 'छवियां',
    es: 'imágenes',
    fr: 'images',
    de: 'Bilder',
    it: 'immagini',
    pt: 'imagens',
    ar: 'الصور',
    zh: '图片',
    ja: '画像',
    ru: 'изображения',
    ko: '이미지',
  },
  'total': {
    en: 'Total',
    hi: 'कुल',
    es: 'Total',
    fr: 'Total',
    de: 'Gesamt',
    it: 'Totale',
    pt: 'Total',
    ar: 'المجموع',
    zh: '总计',
    ja: '合計',
    ru: 'Всего',
    ko: '전체',
  },
  'uncategorized': {
    en: 'Uncategorized',
    hi: 'अवर्गीकृत',
    es: 'Sin categoría',
    fr: 'Non catégorisé',
    de: 'Nicht kategorisiert',
    it: 'Non categorizzato',
    pt: 'Não categorizado',
    ar: 'غير مصنف',
    zh: '未分类',
    ja: '未分類',
    ru: 'Без категории',
    ko: '미분류',
  },
  'imagesWithoutCategory': {
    en: 'Images without a category',
    hi: 'बिना श्रेणी वाली छवियां',
    es: 'Imágenes sin categoría',
    fr: 'Images sans catégorie',
    de: 'Bilder ohne Kategorie',
    it: 'Immagini senza categoria',
    pt: 'Imagens sem categoria',
    ar: 'صور بدون فئة',
    zh: '无类别图片',
    ja: 'カテゴリーなしの画像',
    ru: 'Изображения без категории',
    ko: '카테고리 없는 이미지',
  },
  'prompt': {
    en: 'Prompt',
    hi: 'प्रॉम्प्ट',
    es: 'Indicación',
    fr: 'Invite',
    de: 'Eingabeaufforderung',
    it: 'Prompt',
    pt: 'Prompt',
    ar: 'موجه',
    zh: '提示',
    ja: 'プロンプト',
    ru: 'Подсказка',
    ko: '프롬프트',
  },
  'tapToRead': {
    en: 'Tap to read',
    hi: 'पढ़ने के लिए टैप करें',
    es: 'Toca para leer',
    fr: 'Appuyez pour lire',
    de: 'Tippen zum Lesen',
    it: 'Tocca per leggere',
    pt: 'Toque para ler',
    ar: 'اضغط للقراءة',
    zh: '点击阅读',
    ja: 'タップして読む',
    ru: 'Нажмите, чтобы прочитать',
    ko: '읽으려면 탭하세요',
  },
};

export const useLanguage = () => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('app-language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('app-language', language);
    // Update HTML lang attribute
    document.documentElement.lang = language;
    
    // Dispatch custom event to notify other components
    window.dispatchEvent(new CustomEvent('languageChange', { detail: language }));
  }, [language]);

  // Listen for language changes from other components
  useEffect(() => {
    const handleLanguageChange = (event: CustomEvent) => {
      setLanguage(event.detail);
    };
    
    window.addEventListener('languageChange', handleLanguageChange as EventListener);
    return () => window.removeEventListener('languageChange', handleLanguageChange as EventListener);
  }, []);

  const t = (key: string): string => {
    return translations[key]?.[language] || key;
  };

  return { language, setLanguage, t, languages };
};
