// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vueagetqayqfyakhmolh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ1ZWFnZXRxYXlxZnlha2htb2xoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNTQ5MzIsImV4cCI6MjA2MzkzMDkzMn0.x7e56LXf8Nu3qvCV5JKBvK1ov_Md9u5IUTujV6NGWfA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);